name: Deploy

on:

  workflow_dispatch:

 

jobs:

  deploy:

    runs-on: ubuntu-latest

 

    steps:

      - uses: actions/checkout@v1

 

      - uses: chrnorm/deployment-action@releases/v1

        name: Create GitHub deployment

        id: deployment

        with:

          token: "${{ github.token }}"

          target_url: https://github.com
          environment: dev

          ref: "v2.7.1"


