name: Submit Cloud Build and deploy endpoints

on:
  push:
    paths:
     - '.github/workflows/**'
  repository_dispatch:
    types: [custom_event_type]
  

jobs:
   Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} events."
      - run: echo "hello ${{ toJson(github) }}"
      - run: echo "🎉 The job was automatically triggered by event ${{ github.event.push.push_id}} events."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
