on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: custom action testing again
        uses: actions/checkout@v2
      - name: Run custom action 
        uses:  okimaureen/test_avtion/action1@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Run custom action2 
        uses:  okimaureen/test_avtion/action2@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo  "hello $GITHUB_ACTOR or branch  $GITHUB_REF"
        shell: bash
